export enum ECryptozAnalyticsEvent {
  ABILITY_PLAYED = 'ability_played',
  CARD_BOUGHT_COMPANION = 'card_bought_companion',
  CARD_BOUGHT_DARKNESS_MADNESS = 'card_bought_darkness_madness',
  CARD_BOUGHT_HARBINGER = 'card_bought_harbinger',
  CARD_BOUGHT_MARKET = 'card_bought_market',
  CARD_PLAYED = 'card_played',
  GAME_ENDED = 'game_ended',
  GAME_STARTED = 'game_started',
  MESSAGE_SENT = 'message_sent',
  MODAL_RESPONDED = 'modal_responded',
  MODAL_SHOWN = 'modal_shown',
  PLAYER_READY_TOGGLED = 'player_ready_toggled',
  PLAYER_REMOVED = 'player_removed',
  ROOM_CREATED = 'room_created',
  ROOM_JOINED = 'room_joined',
  ROOM_LEFT = 'room_left',
  ROOM_REMOVED = 'room_removed',
  TURN_ENDED = 'turn_ended',
}
